name: mypresence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  image_picker: 0.8.7+5
  get: 4.6.5
  firebase_core: 2.13.1
  firebase_auth: 4.6.2
  cloud_firestore: 4.8.0
  firebase_storage: 11.2.2
  convex_bottom_bar: 3.2.0
  intl: 0.18.1
  geolocator: 9.0.2
  geocoding: 2.1.0
  syncfusion_flutter_datepicker: 21.2.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/launcher/mypresence_logo.png
  flutter_test: 
    sdk: flutter
  ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/
    - assets/launcher/
  uses-material-design: true

